dev:
  lakehouse: lh_realestate_dev
  workspace_item: realestate-dev
  schema: dbo
  market: AU
  mock_ipstack: true
  lookback_days: 90
  listings_file: listings.csv
  views_file: property_views_5k.csv

test:
  lakehouse: lh_realestate_test
  workspace_item: realestate-test
  schema: dbo
  market: AU
  mock_ipstack: true
  lookback_days: 90
  listings_file: listings.csv
  views_file: property_views_5k.csv

prod:
  lakehouse: lh_realestate_prod
  workspace_item: realestate-prod
  schema: dbo
  market: AU
  mock_ipstack: false
  lookback_days: 90
  listings_file: listings.csv
  views_file: property_views.csv
