dev:
  lakehouse: lh_geo_risk_dev
  workspace_item: geo-risk-dev
  schema: geo
  mock_ipstack: true
  lookback_days: 30
  source_file: events_100.csv

test:
  lakehouse: lh_geo_risk_test
  workspace_item: geo-risk-test
  schema: geo
  mock_ipstack: true
  lookback_days: 30
  source_file: events_5k.csv

prod:
  lakehouse: lh_geo_risk_prod
  workspace_item: geo-risk-prod
  schema: geo
  mock_ipstack: false
  lookback_days: 30
  source_file: events_raw.csv
